# Generated by Django 3.2.13 on 2022-06-20 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Producto')),
                ('valor', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Sala')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre ')),
                ('username', models.CharField(max_length=100, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Contrasena')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda', models.IntegerField(verbose_name='Valor debido')),
                ('pagado', models.IntegerField(verbose_name='Valor pagado')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.sala')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor aportado')),
                ('aporta', models.BooleanField(verbose_name='aporta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.producto')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.sala')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.usuario')),
            ],
        ),
    ]
